# Generated by Django 5.0.4 on 2024-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=50)),
                ('client_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
