# Generated by Django 5.0.4 on 2024-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_address', models.CharField(max_length=50)),
                ('machine_contact', models.CharField(max_length=50)),
                ('machine_serial_number', models.IntegerField()),
            ],
        ),
    ]
