# Generated by Django 5.0.4 on 2024-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0002_machinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='machine_serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
