# Generated by Django 5.0.4 on 2024-05-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0003_alter_machinemodel_machine_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemodel',
            name='machine_contact',
        ),
    ]
