# Generated by Django 5.0.4 on 2024-05-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0004_remove_machinemodel_machine_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemodel',
            name='machine_address',
        ),
    ]
