# Generated by Django 5.0.4 on 2024-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0008_problemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='staus',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Ongoing', 'Ongoing'), ('Processing', 'Processing'), ('NA', 'NA')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
