# Generated by Django 4.2.13 on 2024-05-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0012_problemmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='userprofile',
        ),
    ]
