# Generated by Django 4.2.13 on 2024-05-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0013_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userprofile',
            new_name='profile',
        ),
    ]
