# Generated by Django 4.2.13 on 2024-05-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0014_rename_userprofile_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='userprofile',
        ),
    ]
