# Generated by Django 4.2.13 on 2024-05-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0015_rename_profile_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digidiagno.machinemodel'),
        ),
    ]
