# Generated by Django 4.2.13 on 2024-05-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0017_machinemodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='model',
            field=models.CharField(choices=[('cobas c 111', 'cobas c 111'), ('cobas c 311', 'cobas c 311'), ('cobas e 411', 'cobas e 411'), ('cobas link (all versions)', 'cobas link (all versions)'), ('ISE 9180', 'ISE 9180'), ('COBAS INTEGRA 400 plus', 'COBAS INTEGRA 400 plus'), ('BenchMark GX', 'BenchMark GX'), ('cobas 6000 core unit', 'cobas 6000 core unit'), ('cobas e 601', 'cobas e 601'), ('COBAS AMPLIPREP', 'COBAS AMPLIPREP'), ('COBAS TaqMan', 'COBAS TaqMan'), ('BenchMark XT/LT', 'BenchMark XT/LT'), ('COBAS TaqMan 48', 'COBAS TaqMan 48'), ('FortiGate-50E', 'FortiGate-50E'), ('LightCycler 480', 'LightCycler 480')], default='Processing', max_length=100),
        ),
    ]
