# Generated by Django 4.2.13 on 2024-05-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0018_alter_machinemodel_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ['-id']},
        ),
    ]
