# Generated by Django 4.2.13 on 2024-05-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0020_alter_machinemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemmodel',
            options={'ordering': ['-id']},
        ),
    ]
