# Generated by Django 4.2.13 on 2024-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0022_alter_machinemodel_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='install_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='warranty_amc_status',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50, null=True),
        ),
    ]
