# Generated by Django 4.2.13 on 2024-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0023_clientmodel_install_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='install_loc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
