# Generated by Django 4.2.13 on 2024-05-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0024_machinemodel_install_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinemodel',
            old_name='install_loc',
            new_name='install_location',
        ),
    ]
