# Generated by Django 4.2.13 on 2024-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0027_remove_machinemodel_system_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
