# Generated by Django 4.2.13 on 2024-06-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0028_clientmodel_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
