# Generated by Django 4.2.13 on 2024-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0031_rename_user_engineerprofile_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='is_engineer',
            field=models.BooleanField(default=True),
        ),
    ]
