# Generated by Django 4.2.13 on 2024-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0033_alter_engineerprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
