# Generated by Django 4.2.13 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0034_clientmodel_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
