# Generated by Django 4.2.13 on 2024-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0037_problemmodel_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
