# Generated by Django 4.2.13 on 2024-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0038_alter_problemmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemmodel',
            old_name='problem_area',
            new_name='defects',
        ),
        migrations.RenameField(
            model_name='problemmodel',
            old_name='detailed_desc',
            new_name='service_rendered',
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='status_after_service',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
