# Generated by Django 4.2.13 on 2024-06-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0039_rename_problem_area_problemmodel_defects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='install_location',
        ),
    ]
