# Generated by Django 4.2.13 on 2024-06-12 04:31

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0040_remove_clientmodel_install_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='signature',
            field=jsignature.fields.JSignatureField(),
        ),
    ]
