# Generated by Django 4.2.13 on 2024-06-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidiagno', '0041_alter_clientmodel_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='signature',
        ),
    ]
